version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      # optional: expose if you need outside access (e.g., psql)
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://appuser:apppass@db:5432/appdb
      FRONTEND_URI: "http://localhost:80/api/authorize"
    depends_on:
      - db
    expose:
      - "8000"
    restart: unless-stopped

  runner: 
    build:
      context: .
      dockerfile: Dockerfile.runner
    container_name: runner 
    environment:
      DATABASE_URL: postgres://appuser:apppass@db:5432/appdb
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
